# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: "Test"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        operating-system: ["ubuntu-latest", "windows-latest"]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "Update PHPUnit"
        if: matrix.php-version == '7.4' || matrix.php-version == '8.0'
        run: "composer require --dev phpunit/phpunit:^9.1.5 --update-with-dependencies"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "php -dmemory_limit=-1 vendor/phpunit/phpunit/phpunit"

  compatibility:
    name: "Test Compatibility"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        operating-system: ["ubuntu-latest", "windows-latest"]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Test Compatibility"
        run: "vendor/bin/phpunit test/compat"

  demo-scripts:
    name: "Check Demo Scripts"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Check Demo Scripts"
        run: "test/demo/check-demo.sh"

  coding-standards:
    name: "Check Coding Standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-7.4"
          restore-keys: "php-7.4"

      - name: "Install dependencies"
        run: "composer install"

      - name: "Install CS"
        run: "composer require --dev doctrine/coding-standard:^7.0.2"

      - name: "Coding Standard"
        run: "vendor/bin/phpcs"

  static-analysis-phpstan:
    name: "Static Analysis by PHPStan"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer install"

      - name: "PHPStan"
        run: "vendor/bin/phpstan analyse --memory-limit=-1"

  static-analysis-psalm:
    name: "Static Analysis by Psalm"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-7.4"
          restore-keys: "php-7.4"

      - name: "Install dependencies"
        run: "composer install"

      - name: "Psalm"
        run: "vendor/bin/psalm --shepherd --stats"

  benchmarks:
    name: "Run benchmarks"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-7.4"
          restore-keys: "php-7.4"

      - name: "Install dependencies"
        run: "composer install"

      - name: "Install PhpBench"
        run: "composer require --dev --prefer-dist --prefer-stable --no-interaction --no-progress --no-suggest phpbench/phpbench:^0.17.0"

      - name: "PhpBench"
        run: "vendor/bin/phpbench run --progress=dots --iterations=1"
